/** \file dcs/detail/config.hpp
 *
 * \brief Configuration for this library.
 *
 * [2014-08-31 19:08:50 (CEST)]
 * This is an autogenerated file. Do not edit.
 *
 * \author Marco Guazzone (marco.guazzone@gmail.com)
 */

#ifndef DCS_DETAIL_CONFIG_HPP
#define DCS_DETAIL_CONFIG_HPP


#include <dcs/detail/config/boost.hpp>


#endif // DCS_DETAIL_CONFIG_HPP
