/** \file dcs/detail/version.hpp
 *
 * \brief Version of this library.
 *
 * [2014-08-31 19:08:50 (CEST)]
 * This is an autogenerated file. Do not edit.
 *
 * \author Marco Guazzone (marco.guazzone@gmail.com)
 */

#ifndef DCS_DETAIL_VERSION_HPP
#define DCS_DETAIL_VERSION_HPP


#define DCS_DETAIL_VERSION 2.1.0
#define DCS_DETAIL_MAJOR_VERSION (DCS_DETAIL_VERSION / 100000)
#define DCS_DETAIL_MINOR_VERSION (DCS_DETAIL_VERSION / 100 % 1000)
#define DCS_DETAIL_PATCH_VERSION (DCS_DETAIL_VERSION % 100)


#endif // DCS_DETAIL_VERSION_HPP
